sudo: false

language: java

jdk:
- openjdk8

script: 
# build fat jar
- ./gradlew export.prepareEclipseInstaller

# prepare OomphInstallers (workaround for a non-zero exit code appended)
- java -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar || true

before_deploy:
    # Set up git user name and tag this commit
   - git config --local user.name "Peter Kirschner"
   - git config --local user.email "peter@kirschners.de"
   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
   - git tag $TRAVIS_TAG

deploy:
   provider: releases
      api_key: "GITHUB OAUTH TOKEN"
      file_glob: true
      file: _result/**/*
      skip_cleanup: true
