sudo: false

language: java

jdk:
  - openjdk8

install: ./gradlew --version

script: 

# build fat jar
./gradlew export.prepareEclipseInstaller

# prepare OomphInstallers
java -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar