sudo: false
language: java
jdk:
- openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: 
# build fat jar
- ./gradlew export.prepareEclipseInstaller

# prepare OomphInstallers (workaround for a non-zero exit code appended)
- >
  export version=`grep "base.version" cnf/build.bnd |cut -d'=' -f2`;
  export currDate=`date +'%Y%m%d-%H%M%S'`;
  export gitTag=$(git log --format=%h -1);
  export snapshot=".SNAPSHOT";
  export prerelease=true;
  export TRAVIS_TAG=${version}.${currDate}_${gitTag}${snapshot};
  echo "TRAVIS_TAG=${TRAVIS_TAG}";
  env | sort
#  java 
#  -Dtimestamp=${currDate} 
#  -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar || true

before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "Peter Kirschner"
- git config --local user.email "peter@kirschners.de"
- >
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    export prerelease=false; 
    export snapshot="";
  fi
- export TRAVIS_TAG=${version}.${currDate}_${gitTag}${snapshot}
- git tag $TRAVIS_TAG

# release 
- export RELEASE="IDEfix"
- export RELEASE_NAME="$RELEASE $TRAVIS_TAG"
- export RELEASE_CONTENT="t.b.d. - $RELEASE"
- echo "creating deployment for $RELEASE_NAME with $TRAVIS_TAG"

deploy:
  provider: releases
  prerelease: $prerelease
  api_key:
    secure: In29qlp4RJ9P8Lo4dEZQCKWwaLGzVul/ElMf4kLdOg0MJBtVyTstMR+R61AfCM66VMeF2B1M2McadjOd5d2GWx8cWgPs5bR5tJJZuqztEX2aZYVj/OBO51vhHy3xFuS525JouzomVIuVeOXVIcEl0MarVKdU4lCMuAO8umJlprRJRNRo26B5iYQ2O06V11CxrLMWOfJM6eay7NdX2/W9LcchX7+aqvacjsJ7MX5KsA00AQjRZ9Mzv9nH0YJa6wAL+jDud0IIW1BE3+7IGeAovDwTjMXZY587BPQHFZS0+IBg5NR2qCK2uVVRx3L5qVEOUAEjIuU2I0LB8N4qWBcIEk4pfZXear9SfGm7W8b1PviwSdafmz6BdlQqPALlDfs/Pp+Z9bdU6jRR4H5GQg0dDp6KnO6P6ofuvNirb2JmygOGNC+cuTbgb5oIKfjcIgw5D/MCiJOntiPwUV4WyiewpzHY6mc4kUpRIXZe2T+ZK3UQzyf+JGpTmkKLOnNQ9xXXjJvaEgd8qGa0qX5ATWxZV4Y1KRH9pH0I6CZ+WrqjYM4Sj4aexamPp+PQPnHt7o6gnRy2Bnoz80vEVXoYKtMIwft4IJDvwc70UjUO7auPOzwHCLH7dAZ8YGey5D7wwU0tp3xk5NyDCm6NSRFrfN+tukz9RYwqI2skewIpLPIrJlE=
  file_glob: true
  file: _result/$DATE/$RELEASE/*
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|develop)$
  name: $RELEASE_NAME
  body: $RELEASE_CONTENT
