sudo: false

language: java

jdk:
- openjdk8

script: 
# build fat jar
- ./gradlew export.prepareEclipseInstaller

# prepare OomphInstallers (workaround for a non-zero exit code appended)
- java -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar || true
