sudo: false

language: java

jdk:
- openjdk8

script: 
# build fat jar
- ./gradlew export.prepareEclipseInstaller

# prepare OomphInstallers
- java -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar